name: Update dependencies
on:
  schedule:
    # Every Monday at 00:00.
    - cron: '0 0 * * 1'
  workflow_dispatch:
defaults:
  run:
    shell: bash
jobs:
  update_each_manifest:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1'
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: julia-actions/setup-julia@v1.6.1
        with:
          version: ${{ matrix.version }}
          arch: x64
      - run: cd COVID-19
      - run: println("::set-output name=manifest_version::$(VERSION.major).$(VERSION.minor)")
        shell: julia --color=yes {0}
        id: manifest_version
      - name: Cache artifacts
        uses: actions/cache@v2.1.7
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Manifest.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - run: julia --color=yes -e 'import Pkg; Pkg.Registry.add("General")'
        env:
          JULIA_PKG_SERVER: ""
      - run: julia --color=yes -e 'import Pkg; Pkg.Registry.update()'
      - run: julia --color=yes --project=@. -e 'import Pkg; Pkg.instantiate'
      - run: julia --color=yes --project=@. -e 'import Pkg; Pkg.update()'
      - run: git status
      - uses: actions/upload-artifact@v2.3.1
        with:
          name: manifest_file_for_${{ steps.manifest_version.outputs.manifest_version }}
          path: COVID-19/Manifest.toml
          if-no-files-found: error
